.rubocop.yml, .rubocop_todo.yml, app/models/listing.rb, app/models/user.rb, spec/controllers/listings_controller_spec.rb
- `Metrics/BlockLength` limits the allowed length of `do`/`end` blocks.
Excluded `db/schema.rb` and our specs, since they have legitimately
long blocks.
- `Rails/HasManyOrHasOneDependent` has been disabled. This rule enforces
that we always have a `dependent:` option on `has_many` or `has_one`
relations. Something like `dependent: :destroy` or `dependent:
:nullify`. I'm of the camp that we ought to be very careful what we
destroy, because having relations implicitly deleted when a top level
resource is deleted can have a lot of unintended side effects as the
number of connected relationships grows in an app. Aside from
potentially deleting a lot of extra data, it can also cause N+1
queries against the database. Better to instead add explicit logic for
how a deletion should be executed.
- …
=> Rubocop: fix rubocop on master

.rubocop_todo.yml, bin/setup, config/environments/production.rb, db/schema.rb, spec/controllers/listings_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/currency_spec.rb, test/controllers/locations_controller_test.rb
- `Layout/EmptyLines` allows only one blank line in a row.
- `Layout/EmptyLinesAroundBlockBody` enforces either no empty lines or
one empty line inside of `do`/`end` blocks.
- `Layout/EmptyLinesAroundClassBody` the same but for classes.
- The rest are about spacing inside hashes, blocks, and arrays.
These all have configurations that we can change. For example, on other
projects I've worked on we enforce that there is a blank line padding
class bodies with the `Layout/EmptyLinesAroundClassBody` rule. I don't
really have strong opinions one way or another on these which way we
enforce. My only strong opinion is *that* we enforce them one way or
another.
This also made changes to `db/schema.rb`. Being that this is an
auto-generated file I could go either way on whether we just ignore this …
=> Rubocop: enable spacing rules

.rubocop_todo.yml, spec/controllers/listings_controller_spec.rb, spec/models/currency_listing_spec.rb, spec/models/currency_spec.rb, spec/models/listings_spec.rb, spec/models/user_spec.rb
- `RSpec/ImplicitExpect` says you should not use `should`.
- `RSpec/NamedSubject` wants you to name your subject if you refer to it
at any point in your test. You can use `subject(:my_name) { ... }`. In
this case I just refactored the tests some to avoid use of `subject`.
Controller tests keep a reference to the response as `response` that
can be used.
=> Rubocop: enable Rubocop-RSpec rules

app/models/currencies_listing.rb, app/models/currency.rb, app/models/listing.rb, db/migrate/20180305010436_add_foreign_key_constraints.rb, db/migrate/20180305010835_add_constraints.rb, db/migrate/20180305011401_rename_curreny_listings.rb, db/schema.rb, spec/models/currencies_listing_spec.rb, spec/models/user_spec.rb
- Add foreign key constraints to foreign key columns. These help the
database to ensure referential integrity. When there is a foreign key
constraint, the database won't allow you to remove a record without
dealing in one way or another with its associations. For example, if
we delete a user record, we should decide what to do with their
submitted listings rather than leaving an invalid `submitter_id`.
Likewise, if we remove a `currency` or `listing`, we'll want to make
sure we deal with the join records as well.
- Add a unique index on the join table for `currency_id` and
`listing_id`. This will prevent any weird logic that tries to insert
the same relation twice.
- add `NOT NULL` constraints to a bunch of columns that we presumably
want to not be null. Some of these we may want to …
=> A few updates to the database schema

.rubocop_todo.yml, app/models/listing.rb, app/models/user.rb, config/environments/development.rb
- `Rails/FilePath` requires comma separated path sections. This is
ostensibly for portability so that these commands can run on Windows
systems, since they use `\` instead of `/` for folder delimiters.
Practically speaking, there may never be a case for running this app
on Windows, so my argument in favor of enabling this rule is simply
that it enforces consistency.
- `Rails/InverseOf` requires that we specify an `inverse_of` on custom
model relations.
=> Rubocop: enable Rails rules

.gitignore, .rubocop_todo.yml, spec/controllers/listings_controller_spec.rb, spec/models/listings_spec.rb, spec/spec_helper.rb
Looks like this rule prohibits `=begin`/`=end` style block comments. We
just had the one in our `spec_helper.rb` file, so I removed it, enabling
a bunch of suggested RSpec options. These include:
- enabling `:focus` behavior. We can add a `:focus` option after a spec
description and RSpec will run only that spec. Convenient for
debugging and development.
- enabling failure tracking. RSpec will write spec results out to a
`spec/examples.txt` file so that you can run only failed specs again.
- `disable_monkey_patching!` removes various monkey patches that RSpec
has historically done. Most relevant to us is that it doesn't add the
global function `describe` at the top level, so we need to instead
call `RSpec.describe`.
- A couple of other niceties.
=> Rubocop: enable BlockComments rule & RSpec options

.rubocop.yml, app/controllers/listings_controller.rb, config/environments/development.rb, config/environments/test.rb, spec/controllers/listings_controller_spec.rb
Minor refactors in `ListingsController` to account for this. I also
removed `submitter_id` from permitted params, since that's added in on
the server, and enabled errors being thrown when invalid params are
passed in development or test.
=> Re-enable Metrics/AbcSize rubocop rule

.circleci/config.yml, .circleci/heroku_deploy.sh
- turn on maintenance mode while deploy is in progress to prevent
migration errors and timeouts
- run migrations after deploying
- `set -eu` by default bash scripts continue to run even when an error
is thrown. The `-e` part tells it to bail on the first error rather
than snowballing into bigger issues. The `u` bit prevents using
uninitialized variables.
https://circleci.com/docs/2.0/deployment-integrations/#heroku
=> CircleCI: refactor deploy commands

.circleci/heroku_deploy.sh
It didn't work. Complained about not knowing which app to send to. I
think setting up the remote should fix it.
```
heroku/bin/heroku
▸    Error: No app specified
▸    Usage: heroku maintenance:on --app APP
▸    We don't know which app to run this on.
▸    Run this command from inside an app folder or specify which app to use with --app APP
```
https://circleci.com/gh/helios-coop/corner/205
=> CircleCI: try to fix deploy build

.rubocop.yml, Gemfile, app/controllers/listings_controller.rb, app/controllers/users_controller.rb, config/initializers/assets.rb, config/spring.rb, db/migrate/20180305010835_add_constraints.rb, db/migrate/20180317164008_change_currencies_listings_index.rb, spec/controllers/listings_controller_spec.rb
We discussed this and even though the shorthand is nice, we decided this
is more consistent and less to remember. If some arrays are one format
and others are another it's an extra brain cycle to parse the
difference.
=> Rubocop: swap array shorthand rules

.gitignore
Rather than ignore `.env` from git, we can use `.env.local` for super
secret local stuff, and `.env` for not so super secret local stuff which
I anticipate having a couple of things for soon.  Anything in
`.env.local` will override what's in `.env. `dotenv-rails` looks for a
number of different files.
https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use
=> Tools: un-ignore `.env` file

.rubocop.yml
It got tidied up in another commit.
=> Rubocop: remove geocoder ignores

spec/factories/currencies.rb
I didn't actually mean to check this in. Fixtures supercedes it.
=> Specs: remove currencies from factory

Procfile.dev
`Procfile` is basically a listing of processes that need to be booted to
run an app. Heroku uses this to run different dynos, and locally it can
be used with the `foreman` gem, `foreman start` to use `Procfile` by
default or `foreman start -f Procfile.dev` to use `Procfile.dev`. It's
likely we'll end up wanting slightly different configurations for dev
mode than for production, so it can be handy to have a separate one.
Right now I've changed the `web` command to use `rails s` instead of the
default puma config, since it provides better logging. Down the road we
may want to configure background workers differently on dev, introduce
`mailcatcher` to view emails in dev mode, and run `webpack-dev-server`
for assets.
=> Tools: add Procfile.dev

app/views/listings/_carousel.html.haml
This throws an error by default when no google place is present. Not
sure if this is the best way to resolve it, but it's a start.
=> Errors: return early when no google place

.gitignore, Gemfile, README.md, app/controllers/application_controller.rb, app/controllers/listings_controller.rb, app/views/listings/index.html.haml, app/views/listings/new.html.haml, app/views/mobile_views/listings/index.html.haml, config/initializers/geocoder.rb
Rather than accessing `ENV["GOOGLE_MAPS_API_KEY"]` in different places
this pulls it up into a helper method in `application_controller.rb`.
This way fewer places need to know where the information is coming from.
It can make things easier to test potentially by stubbing the value, and
avoids a global mystery guest, instead using a method call.
I also switched to using `.fetch`, which will throw an error if the key
is not found. This can help reduce head scratching as to why the app
isn't doing what we think it should. Because of this, we'll also need a
`.env.test.local` file, as `.env.local` does not get loaded in test
mode.
=> Refactors: pull `ENV` access into helper

app/views/listings/_carousel.html.haml
Rather than caching each individual image, this caches all of the images
under the listing. If we want to re-fetch the images we can simply
`touch` the listing to invalidate the cache key.
We might want to reconsider this caching at some point, since it only
works for this particular template. If we end up wanting to re-use the
images in another place, we can probably find a way to cache inside the
model instead.
=> Refactors: cache carousel on listing

.rubocop.yml, app/models/listing.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/models/listings_spec.rb
This also required adding `role` to the user factory, and it turns out
we weren't actually validating case insensitivity because the
`google_places_id` used in the test didn't have any letters, so fixed
that.
=> Rubocop: get line length down in listings_spec

spec/rails_helper.rb
Apparently we don't need that...
=> Specs: remove require for capybara/rails

Gemfile, Gemfile.lock, app/controllers/listings_controller.rb, app/models/listing.rb
`acts_as_paranoid` doesn't seem to work too well with Rails 5.2 and the
most recent version is also busted on Rails 5.1. `paranoia` seems to be
a little better maintained, so swapping them out. Unfortunately,
`paranoia` doesn't override the deletion of join records, though, so we
need to manually swap them out, which is why I added
`replace_currencies` in `listing.rb`.
https://github.com/ActsAsParanoid/acts_as_paranoid/issues/88
https://github.com/ActsAsParanoid/acts_as_paranoid/issues/94
https://github.com/ActsAsParanoid/acts_as_paranoid/pull/96
=> Upgrades: replace acts_as_paranoid with paranoia

.circleci/config.yml, Gemfile, Gemfile.lock, README.md
This makes it so that devs don't need to manually install `chromedriver`
and put it in their path somewhere. We might also consider the
`webdrivers` gem at some point if `geckodriver` becomes necessary.
`chromedriver-helper` is just bundled by default in new Rails apps so
figured I'd stick with that for now.
https://github.com/flavorjones/chromedriver-helper
https://github.com/titusfortner/webdrivers
=> Upgrades: introduce chromedriver-helper

Gemfile, Gemfile.lock
These don't need to be locked down in `Gemfile`, as they are locked in
`Gemfile.lock`. As a general philosophy, I don't like to lock things
down in `Gemfile` unless there is an issue of some sort preventing us
from upgrading a particular gem, in which case I'll often add an
explanatory comment or link to an issue on Github for reference.
=> Upgrades: remove version constraints for gems

.circleci/config.yml
The build failed, apparently for lack of some library
`libappindicator3-1`, so we'll try installing it.
https://circleci.com/gh/helios-coop/corner/641
=> CircleCI: try to fix build error on Circle

app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb
Dunno if we'll ever need these, but they're easy to re-introduce if they
do become necessary. And they're keeping us from getting to 100% test
coverage!
=> Specs: remove ActionCable stuff

app/assets/javascripts/application.js
We don't have a js build pipeline right now, so can't use arrow
functions just yet.
=> Errors: remove es6 arrow function

.rubocop.yml, app/controllers/listings_controller.rb
Remove the extra online-only listings when someone is searching by name or category. 
They are being used mostly for location searches so results don't look so empty.
=> Remove online only listings

.rubocop.yml, app/models/category.rb, db/seeds.rb, spec/db/seeds_spec.rb
Now we can run `rake db:seed` to load this data. Not a big deal, but
there's an N+1 query here, so if we get around to integrating a bulk
import library such as `activerecord-import`, might be worth swapping in
here as well.
https://github.com/zdennis/activerecord-import
=> Seeds: move category creation method to seeds

Rakefile, db/mock_data.rb
We have `db/seeds.rb`, but I treat this as a file that can be run in
production, whereas we also want dev-only data, like a fake user to poke
around with. For this, I added a `db/mock_data.rb` file, and enhanced
the `rake db:reset` command to populate the database from this file. We
can also use `rake db:populate` to just add the records and nothing
else. I `break` early to prevent accidentally running this in
production.
=> Seeds: add mock data for dev mode

app/views/listings/_google_place_details.html.haml, app/views/mobile_views/listings/_google_place_details.html.haml
As near as I can tell, the `else` case cannot be hit. These templates
are rendered from two places. From `listings#index` they don't even get
rendered if there is no `@listing`, and from `listings#show` an error
would be thrown in the controller if a listing could not be found. There
are similiar conditionals in the `_non_google_place_details` templates,
but these can get hit, since it gets rendered if no place was found.
Might be worth pulling these out into a separate template, however.
=> Views: remove conditional for google place details

.haml-lint_todo.yml, app/views/listings/_form.html.haml
We only need to specify `class:` when we have some dynamic value.
https://github.com/brigade/haml-lint/blob/master/lib/haml_lint/linter/README.md#classattributewithstaticvalue
=> haml-lint: enable ClassAttributeWithStaticValue rule

app/models/user.rb
`password` is ephemeral on user, so it will be `nil` if you're updating
another attribute, and fail the validation. Now we only validate the
length if it's present, meaning, presumably, that it has been passed
from the client side.
=> Validations: allow_nil for user password

.env, app/controllers/application_controller.rb, app/controllers/listings_controller.rb, spec/support/geocoder.rb
This adds a method in `ApplicationController` to fake `REMOTE_ADDR` for
geocoding based on IP address. The default IP is in San Francisco. If we
want to override it, we can do so with `REMOTE_ADDR=1.1.1.1 rails s` or
by adding it in `.env.local`.
Side note, according to the docs, `request.location` is slow due to it
hitting a 3rd party API, so we'll probably want to find a way to
background it at some point.
https://github.com/alexreisner/geocoder#geocoding-is-slow
=> Geocoder: enable ip location for dev/test mode

.haml-lint_todo.yml, app/views/layouts/_header.html.haml, app/views/listings/index.html.haml, app/views/mobile_views/layouts/_header.html.haml, app/views/mobile_views/listings/index.html.haml
This requires that html ids be in "lisp case" (or "kebab case").
https://github.com/brigade/haml-lint/blob/master/lib/haml_lint/linter/README.md#idnames
=> haml-lint: enable IdNames rule

.haml-lint_todo.yml, .rubocop.yml
There are a bunch of violations, so going to tackle these a few at a
time.
=> haml-lint: temporarily disable rubocop rules

app/controllers/listings_controller.rb, app/models/currencies_listing.rb, app/models/listing.rb, app/views/listings/_form.html.haml, app/views/listings/_google_places_form.html.haml, spec/controllers/listings_controller_spec.rb, spec/models/currencies_listing_spec.rb
Passes back `currency_ids` and nests them under the `listing` params. I
needed to disable the validation on `CurrenciesListing` because it
validates before the listing saves, so because the listing hasn't been
saved, yet, the id will not be present. It will, however, be present
when the `CurrenciesListing` record is auto-saved after the `Listing`.
This is angling towards using the `collection_check_boxes` form helper.
https://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_check_boxes
=> Views: switch to using currency_ids for params

.gitignore, config/environments/development.rb
This way there's one thing nobody has to have configured with AWS.
=> Storage: configure file storage to use local

app/views/listings/_form.html.haml
This form validation makes you upload an image when updating a listing,
even when the listing already has an image. I opted to make it required
only for new listings, though another alternative would be to make it
`@listing.images.empty?`. The reason I chose this is that a user might
want to update the record for another reason, so doesn't make sense for
someone to have to upload an image in that case.
=> Views: only require images for new records

app/controllers/listings_controller.rb
When the listing is not valid, it re-renders the `new` template, but
throws an error because it's missing these variables.
=> Bugs: fix else case when creating listing

app/controllers/application_controller.rb, app/views/listings/_carousel.html.haml, app/views/listings/_non_google_place_details.html.haml, app/views/listings/index.html.haml, app/views/mobile_views/listings/_non_google_place_details.html.haml, app/views/mobile_views/listings/index.html.haml
Since we use this in so many places, seems worth pulling out rather than
copying and pasting it over and over. I made a judgement call on
`width:`, as in some places the width was different in the url than
specified for the image. Not sure if this was intentional, but I opted
to just use the url width.
=> Views: add `satoshi_image` helper
