Gemfile, Gemfile.lock
Will need to configure on Heroku.
=> add Honeybadger gem

Gemfile, Gemfile.lock, Procfile, config/application.rb
Not much going on here, just getting it at the ready for when we need
some background jobs.
=> introduce Sidekiq

.rubocop_todo.yml, Gemfile, app/controllers/listings_controller.rb, app/controllers/users_controller.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb
- Shortened comments in Gemfile
- Pulled permitted params out into a constant
- Wrap parameters in specs
=> Rubocop: reduce line length to 120

Gemfile, Gemfile.lock, spec/controllers/listings_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/listings.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/rails_helper.rb
This adds test factories to make setting up records for the tests much
cleaner. I also tossed in the `Faker` gem for some fun test data.
http://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md
https://github.com/stympy/faker
=> introduce FactoryBot

.circleci/heroku_deploy.sh
It doesn't like the login info. Another attempt at a fix.
https://devcenter.heroku.com/articles/git#ssh-git-transport
=> CircleCI: try configuring the deploy with ssh

app/views/listings/index.html.haml
=> Revert "Test build"

.gitignore, Gemfile, spec/rails_helper.rb
It runs automatically, so just run `rspec spec/` and then open up
`coverage/simplecov/index.html` in your browser.
=> Coverage: introduce SimpleCov

app/controllers/admin/currencies_controller.rb
They're aliased under the hood, so we can use `update` for everything.
=> Rails: rename `update_attributes` -> `update`

app/controllers/listings_controller.rb, app/models/listing.rb
A handful of small tidy ups in `listings_controller.rb` and
`listing.rb`, taking advantage of some snazzy rubyisms.
=> Refactors: minor cleanups around listing

app/assets/stylesheets/listings.scss, app/views/listings/_details.html.haml, app/views/listings/index.html.haml, app/views/mobile_views/listings/_details.html.haml
https://app.honeybadger.io/projects/55247/faults/37337966#notice-trace
=> Fix exception when missing google place

.rubocop.yml, app/controllers/listings_controller.rb, app/poros/google_place_params_parser.rb
This creates a new ruby object to encapsulate the params parsing from
the google places api.
=> Rubocop: pull place params parsing out into poro

spec/jobs/application_job_spec.rb, spec/mailers/application_mailer_spec.rb
We'll probably be wanting to use these eventually, so adding simple
tests to cover the files.
=> Specs: add basic test coverage

app/models/categories_listing.rb, app/models/category.rb, app/models/listing.rb, db/migrate/20180502172147_create_categories.rb, db/schema.rb, spec/factories/categories.rb, spec/models/categories_listing_spec.rb, spec/models/category_spec.rb, spec/models/listing_spec.rb
https://trello.com/c/bDPHNHIi/79-add-categories-to-search-function
Add category and categories_listings models.
=> add categories model

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/listings.scss, app/controllers/listings_controller.rb, app/views/listings/_form.html.haml, app/views/listings/_non_google_place_details.html.haml, lib/assets/category_list.rb
Not sure why multiple categories are not getting passed from the form to the controller.
=> Use semantic-ui to choose categories

.rubocop.yml, app/models/listing.rb
Needed to add a `.joins(:categories)` to get the `:category` one to
work.
=> Rubocop: condense method in listing

Gemfile, Gemfile.lock, app/controllers/listings_controller.rb, spec/controllers/listings_controller_spec.rb, spec/rails_helper.rb, spec/support/vcr.rb, spec/vcr_cassettes/Tierra_Mia.yml
VCR records web requests and plays them back. It will also throw an
error if our tests try to make a web request without a cassette being
specified. This also checks in a cassette, assuming we'll probably want
to have them always run offline after the first check, with maybe an
occasional refresh.
=> Specs: introduce VCR

app/assets/stylesheets/listings.scss, app/views/listings/_form.html.haml
Appends image previews to file uploader
=> Preview Images

app/controllers/listings_controller.rb
Both branches just get the center point from the IP. If we want to make
them different we should probably add a card to Trello.
=> Geocoder: remove duplicate branch in controller

app/views/listings/_google_place_details.html.haml
The method name on currency is `#icon_path`.
=> Fixing method_name

app/views/listings/_google_place_details.html.haml
We were just hard-coding before. Now use level from google.
=> Use google price level

.rubocop.yml, app/views/admin/currencies/_form.html.haml, app/views/layouts/_search.html.haml, app/views/layouts/application.html.haml, app/views/listings/_form.html.haml, app/views/listings/_google_place_details.html.haml, app/views/listings/_google_places_form.html.haml, app/views/listings/index.html.haml, app/views/listings/new.html.haml, app/views/listings/show.js.haml, app/views/mobile_views/layouts/_search.html.haml, app/views/mobile_views/listings/_google_place_details.html.haml, app/views/mobile_views/listings/index.html.haml, app/views/mobile_views/listings/show.js.haml, app/views/sessions/new.html.haml, app/views/users/new.html.haml
Switched everything to double quotes, including inside of interpolation.
=> haml-lint: enable string quote lints

Gemfile, app/assets/stylesheets/corner-shared.scss, app/views/mobile_views/layouts/_header.html.haml, app/views/mobile_views/layouts/_secondary_header.html.haml, app/views/mobile_views/listings/index.html.haml
Also moving the 'Add A Listing' link so it's visible at all times.
=> Fix mobile navbar so it opens and collapses correctly

app/assets/stylesheets/sessions.scss, app/views/sessions/new.html.haml, app/views/users/new.html.haml, config/initializers/assets.rb
Clean up new user and log in pages
=> Cleaning up styles

app/controllers/users_controller.rb, app/views/layouts/_header.html.haml, app/views/mobile_views/layouts/_header.html.haml, app/views/users/contact.html.haml, config/routes.rb
Code to send message coming in next PR.
=> Add view for contact form

app/views/listings/_form.html.haml
Force a manually added listing to upload at least one image
=> That was easy

app/views/admin/currencies/index.html.haml, app/views/listings/_add_listing.html.haml, app/views/listings/_carousel.html.haml, app/views/listings/_form.html.haml, app/views/listings/_google_places_form.html.haml, app/views/listings/_non_google_place_details.html.haml, app/views/listings/index.html.haml, app/views/listings/show.js.haml, app/views/mobile_views/layouts/_header.html.haml, app/views/mobile_views/listings/index.html.haml, app/views/mobile_views/listings/show.js.haml
- remove extra lines
- un-wrap a couple of elements
=> Views: adjust spacing

Gemfile, Gemfile.lock
I installed brakeman and ran the report. Seems like you just need it in your laptop gems. Not sure what it does inside the actual gemfile.
=> Adding Brakeman to dev
